preprocessor

diff --git a/0x00-hello_world/0-preprocessor b/0x00-hello_world/0-preprocessor
--- a/0x00-hello_world/0-preprocessor
+++ b/0x00-hello_world/0-preprocessor
@@ -1,2 +1,8 @@
-#!bin/bash
-gcc $CFILE -E  -o  c
+#!/bin/bash
+if [ -z "$CFILE" ]; then
+    echo "Error: CFILE environment variable not set"
+    exit 1
+fi
+
+gcc -E "$CFILE" -o c
+
